name: Docker Image CI
on:
  push:
    branches:
    - '**'
    - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: rlespinasse/github-slug-action@1.1.0
    - name: Build and Push the Docker image
      run: |
        DOCKER_TAG="${GITHUB_REF_SLUG}-${GITHUB_SHA_SHORT}"
        DOCKER_IMAGE="takitake/spring-boot-demo:${DOCKER_TAG}"
        docker build . --file Dockerfile --tag ${DOCKER_IMAGE}
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username takitake --password-stdin
        docker push ${DOCKER_IMAGE}
