name: Docker Image Promotion
on:
  pull_request:
    types:
    - 'closed'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Promote the Docker image
      run: |
        cat $GITHUB_EVENT_PATH
